// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:zentime/logic/workday.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DayTypeAdapter());
    registerAdapter(EntryTypeAdapter());
    registerAdapter(TimeEntryAdapter());
    registerAdapter(WorkDayAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DayTypeAdapter());
    registerAdapter(EntryTypeAdapter());
    registerAdapter(TimeEntryAdapter());
    registerAdapter(WorkDayAdapter());
  }
}
